-- Analysis fixture approximating the as-is Oracle side of ROLLS.
-- Not used by the local macOS runtime.
CREATE TABLE CUSTOMER (
 CUSTOMER_ID NUMBER(6) NOT NULL,
 NAME VARCHAR2(100) NOT NULL,
 STATUS VARCHAR2(20) NOT NULL,
 CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE PRODUCT (
 PRODUCT_ID NUMBER(6) NOT NULL,
 NAME VARCHAR2(100) NOT NULL,
 PRICE NUMBER(9,2) NOT NULL,
 STOCK NUMBER(7) NOT NULL,
 CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);
CREATE TABLE ORDERS (
 ORDER_ID NUMBER(6) NOT NULL,
 CUSTOMER_ID NUMBER(6) NOT NULL,
 STATUS VARCHAR2(20) NOT NULL,
 AMOUNT NUMBER(9,2) NOT NULL,
 CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);
CREATE TABLE ORDER_HISTORY (
 HISTORY_ID NUMBER(10) NOT NULL,
 ORDER_ID NUMBER(6) NOT NULL,
 EVENT_TYPE VARCHAR2(30) NOT NULL,
 EVENT_TS DATE NOT NULL
);
