-- Oracle-like logical schema used as modernization-analysis input.
CREATE TABLE CUSTOMER (
  CUSTOMER_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  STATUS VARCHAR(20) NOT NULL
);
CREATE TABLE PRODUCT (
  PRODUCT_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PRICE DECIMAL(9,2) NOT NULL,
  STOCK INTEGER NOT NULL
);
CREATE TABLE ORDERS (
  ORDER_ID INTEGER PRIMARY KEY,
  CUSTOMER_ID INTEGER NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  AMOUNT DECIMAL(9,2) NOT NULL
);
CREATE TABLE ORDER_LINE (
  ORDER_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL
);
CREATE TABLE ORDER_HISTORY (
  HISTORY_ID INTEGER PRIMARY KEY,
  ORDER_ID INTEGER NOT NULL,
  EVENT_TYPE VARCHAR(30) NOT NULL,
  EVENT_TS VARCHAR(30) NOT NULL
);
CREATE TABLE STOCK_MOVEMENT (
  MOVEMENT_ID INTEGER PRIMARY KEY,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  MOVEMENT_TYPE VARCHAR(20) NOT NULL
);
